### ISSUE TITLE
Latest commit has session.json incompatibility with olfactometer_calibration workflow

### ISSUE THREAD

**Issue by tiffanyona** [AllenNeuralDynamics/Aind.Behavior.Services#127]
Workflow expects a field in session.json called "RemotePath". This is not a field in the current session.json.

**Comment by bruno-f-cruz** [comment]
The most sustainable solution is to move this calibration routine to its own repository and maintaining it there. I will add it to the todo list.

**Comment by bruno-f-cruz** [comment]
Supersededby #129 and #136
