### ISSUE TITLE
Add check for sufficient HardDrive storage

### ISSUE THREAD

**Issue by tiffanyona** [AllenNeuralDynamics/Aind.Behavior.Services#38]
Before running a behavioral session, check if there is sufficient storage left. Otherwise session will crash and it is unrecoverable. 

Temp. plan:
1. RAs check capacity manually and if needed 2. 
2. Tiffany removes and deletes files when needed and periodically.

**Comment by bruno-f-cruz** [comment]
Fixed via #93
